FROM php:7.1-fpm

RUN apt-get update \
	&& apt-get install -y wget tar \
	&& cd ~ \
	&& wget https://www.imagemagick.org/download/ImageMagick-7.0.7-37.tar.gz \
	&& tar -zvxf ImageMagick-7.0.7-37.tar.gz \
	&& cd ImageMagick-7.0.7-37 \
	&& ./configure --prefix=/usr/local/imagemagick \
	&& make \
	&& make install 

#RUN pecl install imgick
